### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by mrchypark** [mrchypark/Elbird#6]
엘버드는

엘리펀트 버드의 줄임표현으로 kiwi 패키지를 wrapping 했다는 의미를 담기 위해 이름을 고려했음
(물론 kiwi 패키지의 kiwi는 과일 키위같지만...)

(암튼) 패키지 로고가 필요함.

**Comment by mrchypark** [comment]
https://pnghut.com/png/0xAeEQVWK0/flightless-bird-moa-common-ostrich-clip-art-animal-transparent-png

**Comment by jhk0530** [comment]
![Elkiwi](https://user-images.githubusercontent.com/6457691/97802998-9113f180-1c8a-11eb-96ff-cb7601927ebb.png)

키위 색상 느낌으로 Hexsticker 만들어봤습니다~

**Comment by mrchypark** [comment]
이 배치와 색상 조합이 훨씬 좋네요 ㄷㄷㄷ 

![logo](https://user-images.githubusercontent.com/6179259/97803479-27491700-1c8d-11eb-908b-fd76684e4533.png)

**Comment by jhk0530** [comment]
오...

**Comment by mrchypark** [comment]
역시 똥손이라 어느게 좋은지, 뭐가 방법인지 전혀 모르겠습니다. ㅠㅠ

근데 색 조합에 키위색을 넣으신건 정보를 전달하기에 좋은거 같아요! 반영해보겠습니다.
제가 만든 Hexsticker 는 R/.logo.R 에 있습니다.

**Comment by jhk0530** [comment]
원래 이런건 역시 패키지 주인맘대로죠

**Comment by mrchypark** [comment]
@jhk0530 ㅋㅋㅋ 색조합이 아주 마음에 들게 나왔어요! 아주 감사드려요 ㅎㅎ
![logo](https://user-images.githubusercontent.com/6179259/97803758-b86cbd80-1c8e-11eb-946d-f646612907ba.png)

**Comment by mrchypark** [comment]
@jhk0530 정말 감사드립니다. :)

![image](https://user-images.githubusercontent.com/6179259/97803787-f5d14b00-1c8e-11eb-92fa-c82ba82ec768.png)
